# Generated by Django 4.2.1 on 2023-05-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_image',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(default='', upload_to='videos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
